### ISSUE TITLE
Feature Request: Capture Memcached Metrics

### ISSUE THREAD

**Issue by j0sh3rs** [newrelic/nri-couchbase#25]
##### Description of the problem

The request is relatively simple in ask, and I'm sure less so in implementation :)

Couchbase as a product can also act as a simple memcached server, and exposes a lot of memcached metrics that are not currently collected by this integration. The tl;dr would be to capture all these available metrics for memcached buckets that get exposed by Couchbase.

Ideally, one would not also need to deploy the memcached integration on a Couchbase server as well, but assuming that's the path of least resistance, that path also has issues (this may not be the right place for those, but I'll attempt to capture them and can always move the issue).

Attempting to use the memcached integration directly against Couchbase's implementation resulted in incomplete data being sent to NewRelic, as well as caused consistent coredumps on our Couchbase 4.0.x instances (suggesting that some of the memcached integration polling was problematic for Couchbase itself). I'm unable to provide an example coredump, but the problem would be easily reproduced.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment]
@j0sh3rs Thanks for the request! I apologize for the slow response -- this one fell through the cracks a bit. I know I investigated this at one point (maybe indirectly at your request?), and I was able to collect stats from Memcached buckets successfully (example below). Were there additional metrics you were looking for, and is there a reason this doesn't work instead of attempting to get the memcached integration to monitor couchbase? 

```
  {
      "bucket.activeResidentItemsRatio": 100,
      "bucket.averageDiskCommitTimeInMilliseconds": 0,
      "bucket.averageDiskUpdateTimeInMilliseconds": 0,
      "bucket.cacheMissRatio": 0,
      "bucket.currentConnections": 286,
      "bucket.dataUsedInBytes": 138883292,
      "bucket.decrementHitsPerSecond": 0,
      "bucket.decrementMissesPerSecond": 0,
      "bucket.deleteHitsPerSecond": 0,
      "bucket.deleteMissesPerSecond": 0,
      "bucket.diskCreateOperationsPerSecond": 0,
      "bucket.diskFetchesPerSecond": 0,
      "bucket.diskUpdateOperationsPerSecond": 0,
      "bucket.diskUsedInBytes": 209126646,
      "bucket.diskWriteQueue": 0,
      "bucket.ejectionsPerSecond": 0,
      "bucket.evictionPolicy": "valueOnly",
      "bucket.evictionsPerSecond": 0,
      "bucket.getHitsPerSecond": 0,
      "bucket.getMissesPerSecond": 0,
      "bucket.hitRatio": 0,
      "bucket.incrementHitsPerSecond": 0,
      "bucket.incrementMissesPerSecond": 0,
      "bucket.itemCount": 31591,
      "bucket.memoryHighWaterMarkInBytes": 0,
      "bucket.memoryLowWaterMarkInBytes": 0,
      "bucket.memoryUsedInBytes": 157194480,
      "bucket.metadataInRAMInBytes": 0,
      "bucket.missesPerSecond": 0,
      "bucket.outOfMemoryErrorsPerSecond": 0,
      "bucket.overheadInBytes": 0,
      "bucket.pendingResidentItemsRatio": 100,
      "bucket.quotaUtilization": 49.97077941894531,
      "bucket.readOperationsPerSecond": 0,
      "bucket.readRatePerSecond": 384.8484848484849,
      "bucket.replicaIndex": 0,
      "bucket.replicaNumber": 2,
      "bucket.replicaResidentItemsRatio": 100,
      "bucket.residentItemsRatio": 100,
      "bucket.temporaryOutOfMemoryErrorsPerSecond": 0,
      "bucket.threadsNumber": 3,
      "bucket.totalOperationsPerSecond": 0,
      "bucket.writeOperationsPerSecond": 0,
      "bucket.writeRatePerSecond": 9152.525252525253,
      "displayName": "memcached",
      "entityName": "cb-bucket:memcached",
      "event_type": "CouchbaseBucketSample"
    }
```

**Comment by ccheek21** [comment]
Closing for now, feel free to re-open if this is still a problem
