### ISSUE TITLE
Feature Request: Add Node Name to Bucket Sample Data

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nri-couchbase#35]
##### Add Node Name

It would be valuable to have the node name available for reporting purposes in the Bucket sample data.

##### OS

- [x] All of them

**Comment by camdencheek** [comment]
Hi @icpenguins -- Buckets don't belong to any specific node, so I don't think there is a meaningful way to attach the node name to the bucket

**Comment by icpenguins** [comment]
@camdencheekm yeah, the call for stats doesn't seem to get the node details. However, it appears that a call to a single bucket for information should return an `[]nodes` property. I guess the question is how to report on the array?

[Single Bucket](https://developer.couchbase.com/documentation/server/3.x/admin/REST/rest-bucket-info.html)

**Comment by camdencheek** [comment]
They should use the node entities if they want node stats
