### ISSUE TITLE
Decoding JSON fails with unexpected string in response

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nri-couchbase#38]
#### JSON Property Returns "undefined" when `int` is Expected

An error is logged when trying to decode a JSON response from `/pools/default`. It is likely that the call to json.NewDecoder(...).Decode(model) is failing when attempting to decode the "undefined" string in the JSON property `percentage`.

**This failure appears to stop allowing reporting to occur for the node.**

[`err = json.NewDecoder(response.Body).Decode(model)`](https://github.com/newrelic/nri-couchbase/blob/c721f68e7324873d24b6dbfee4e2ae5341e72679/src/client/client.go#L89)

##### Log Message

```text
time="2020-01-31T22:41:30-08:00" level=error msg="Integration command failed" error="exit status 1" instance= integration=com.newrelic.couchbase prefix=config/couchbase stderr="[ERR] Could not complete collection: received an unexpected response from endpoint '/pools/default': json: cannot unmarshal string into Go struct field ViewFragmentationThreshold.percentage of type int\n" working-dir=/var/db/newrelic-infra/newrelic-integrations
```

##### JSON Property

The JSON property returns the value of "undefined" where an integer is expected.

```json
"viewFragmentationThreshold":{"percentage":"undefined","size":"undefined"}
```

##### [Couchbase Cluster-wide Settings](https://docs.couchbase.com/server/current/rest-api/rest-autocompact-get.html#cluster-wide-response)

This appears to happen when calling `/settings/autoCompaction`. However, it would be good to ensure that any values returned as "undefined", a valid JSON type, for numerics can be handled accordingly.

```json
{
    "autoCompactionSettings": {
        "databaseFragmentationThreshold": {
            "percentage": undefined,
            "size": "undefined"
        },
        "parallelDBAndViewCompaction": false,
        "viewFragmentationThreshold": {
            "percentage": undefined,
            "size": "undefined"
        }
    },
    "purgeInterval": 3
}
```

##### OS

- [x] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)

**Comment by camdencheek** [comment]
Hi @icpenguins - can you confirm whether the endpoint returns the string `"undefined"` or the literal `undefined`? The documentation lists both in its `viewCompactionThreshold`, but the example you gave is all quoted

**Comment by icpenguins** [comment]
@camdencheek it is returned as a string; which is ironic because that is the opposite of what the Couchbase documentation example shows. However, in a conversation with @mariomac [207](https://github.com/newrelic/infra-integrations-sdk/issues/207), JSON does not currently support undefined as a value.

**Comment by camdencheek** [comment]
@icpenguins The quick fix here is to allow strings for that field. However, without knowing which fields can be arbitrarily sent back as strings rather than numbers, it's difficult to say if they will hit this for other fields, or if other fields will ever send back undefined.

I'll make a PR for that, but I can't guarantee that they won't continue to see issues elsewhere.

**Comment by icpenguins** [comment]
@camdencheek from my reading over the weekend, these are the places we could expect to see `undefined` passed as a string; percentage and size of both these properties. In my opinion, this should be returned as a `null` or the property not passed at all; hence `undefined` ;)

```json
"databaseFragmentationThreshold": {
   "percentage":30,
   "size":"undefined"
},
"viewFragmentationThreshold": {
   "percentage":"undefined",
   "size":"undefined"
}
```

**Comment by mariomac** [comment]
@icpenguins is candem patch fixing the problem? I wouldn't expect so. If not, I will provide another patch, which may be a bit shoddy as long as despite ECMASrcipt supports `undefined` and `Inf`, JSON does not and we probably need a way to "manually" pre-process the Couchbase incorrect JSON to eliminate those unquoted `undefined`
